# Unified configuration for batch + single runs

flmm:
  # Vendored mmengine config for the router (path is relative to this YAML inside config/)
  config_path: ../rag_flmm/configs/llava/frozen_llava_1_5_vicuna_7b_unet_sam_l_refcoco_png.py
  checkpoint_path: null
  device: cuda
  rag_threshold: null
  router_kwargs: {}
  # Trained router checkpoint (directory with last_checkpoint or a .pth file)
  router_checkpoint: /dataset/router/routernetv3/iter_70000.pth

wikipedia:
  # Vendored wikipedia project root and its native YAML
  root: /home/sjkim/flmmwiki/flmm_wiki_rag/wikipedia
  config_path: config.yaml
  enable_nli: true
  enable_vlm: true
  # You can override dataset/image/KB paths here if you don't want to edit wikipedia/config.yaml
  overrides: {}

runtime:
  generate_answer: true
  max_new_tokens: 64
  pretty_print: true
  json_output: null

# Optional auth section. You may temporarily paste your HF token here during
# development, then clear it before committing. Alternatively use
# environment variable HF_TOKEN or config/local.yaml (gitignored).
auth:
  hf_token:##여기 토큰넣기
